"""initial schema snapshot

Revision ID: 6edcb0a00c24
Revises: 
Create Date: 2026-04-10 11:21:55.219236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6edcb0a00c24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('active_calories', sa.Integer(), nullable=True),
    sa.Column('workout_type', sa.String(length=50), nullable=True),
    sa.Column('workout_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_records_date'), 'activity_records', ['date'], unique=False)
    op.create_index(op.f('ix_activity_records_user_id'), 'activity_records', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('routing_tier', sa.String(length=20), nullable=True),
    sa.Column('routing_reason', sa.String(length=255), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('safety_flagged', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('feedback', sa.String(length=10), nullable=True),
    sa.Column('feedback_at', sa.DateTime(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('health_context', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('device_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_table('garmin_daily_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('avg_heart_rate', sa.Float(), nullable=True),
    sa.Column('max_heart_rate', sa.Float(), nullable=True),
    sa.Column('resting_heart_rate', sa.Float(), nullable=True),
    sa.Column('stress_avg', sa.Float(), nullable=True),
    sa.Column('body_battery_high', sa.Integer(), nullable=True),
    sa.Column('body_battery_low', sa.Integer(), nullable=True),
    sa.Column('active_minutes', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garmin_daily_records_date'), 'garmin_daily_records', ['date'], unique=False)
    op.create_index(op.f('ix_garmin_daily_records_user_id'), 'garmin_daily_records', ['user_id'], unique=False)
    op.create_table('garmin_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('session_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garmin_tokens_user_id'), 'garmin_tokens', ['user_id'], unique=False)
    op.create_table('health_metric_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_metric_records_date'), 'health_metric_records', ['date'], unique=False)
    op.create_index(op.f('ix_health_metric_records_metric_type'), 'health_metric_records', ['metric_type'], unique=False)
    op.create_index(op.f('ix_health_metric_records_source'), 'health_metric_records', ['source'], unique=False)
    op.create_index(op.f('ix_health_metric_records_user_id'), 'health_metric_records', ['user_id'], unique=False)
    op.create_table('meal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('photo_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_records_date'), 'meal_records', ['date'], unique=False)
    op.create_index(op.f('ix_meal_records_user_id'), 'meal_records', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('morning_brief', sa.Boolean(), nullable=False),
    sa.Column('coaching_nudge', sa.Boolean(), nullable=False),
    sa.Column('bedtime_coaching', sa.Boolean(), nullable=False),
    sa.Column('streak_alerts', sa.Boolean(), nullable=False),
    sa.Column('weekly_review', sa.Boolean(), nullable=False),
    sa.Column('workout_reminders', sa.Boolean(), nullable=False),
    sa.Column('health_alerts', sa.Boolean(), nullable=False),
    sa.Column('nudge_frequency', sa.String(length=20), nullable=False),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=False),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('notification_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('device_token_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_records_category'), 'notification_records', ['category'], unique=False)
    op.create_index(op.f('ix_notification_records_user_id'), 'notification_records', ['user_id'], unique=False)
    op.create_table('notification_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('context', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_templates_category'), 'notification_templates', ['category'], unique=False)
    op.create_index(op.f('ix_notification_templates_context'), 'notification_templates', ['context'], unique=False)
    op.create_table('oura_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oura_tokens_user_id'), 'oura_tokens', ['user_id'], unique=False)
    op.create_table('peloton_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('peloton_user_id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peloton_tokens_user_id'), 'peloton_tokens', ['user_id'], unique=False)
    op.create_table('sleep_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('efficiency', sa.Float(), nullable=True),
    sa.Column('total_sleep_seconds', sa.Integer(), nullable=True),
    sa.Column('deep_sleep_seconds', sa.Integer(), nullable=True),
    sa.Column('rem_sleep_seconds', sa.Integer(), nullable=True),
    sa.Column('light_sleep_seconds', sa.Integer(), nullable=True),
    sa.Column('hrv_average', sa.Float(), nullable=True),
    sa.Column('resting_hr', sa.Float(), nullable=True),
    sa.Column('readiness_score', sa.Integer(), nullable=True),
    sa.Column('bedtime_start', sa.String(length=5), nullable=True),
    sa.Column('bedtime_end', sa.String(length=5), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_records_date'), 'sleep_records', ['date'], unique=False)
    op.create_index(op.f('ix_sleep_records_user_id'), 'sleep_records', ['user_id'], unique=False)
    op.create_table('source_priorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('metric_category', sa.String(length=50), nullable=False),
    sa.Column('priority_order', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_priorities_user_id'), 'source_priorities', ['user_id'], unique=False)
    op.create_table('user_correlations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('source_metric', sa.String(length=100), nullable=False),
    sa.Column('target_metric', sa.String(length=100), nullable=False),
    sa.Column('lag_days', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('pearson_r', sa.Float(), nullable=False),
    sa.Column('spearman_r', sa.Float(), nullable=False),
    sa.Column('p_value', sa.Float(), nullable=False),
    sa.Column('fdr_adjusted_p', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('confidence_tier', sa.String(length=30), nullable=False),
    sa.Column('literature_match', sa.Boolean(), nullable=False),
    sa.Column('literature_ref', sa.Text(), nullable=True),
    sa.Column('effect_size_description', sa.Text(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_correlations_user_id'), 'user_correlations', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apple_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height_inches', sa.Integer(), nullable=True),
    sa.Column('weight_lbs', sa.Float(), nullable=True),
    sa.Column('target_weight_lbs', sa.Float(), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('training_experience', sa.String(length=50), nullable=True),
    sa.Column('training_days_per_week', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_apple_user_id'), 'users', ['apple_user_id'], unique=True)
    op.create_table('workout_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('workout_type', sa.String(length=50), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('avg_heart_rate', sa.Float(), nullable=True),
    sa.Column('max_heart_rate', sa.Float(), nullable=True),
    sa.Column('avg_output', sa.Float(), nullable=True),
    sa.Column('instructor', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_records_date'), 'workout_records', ['date'], unique=False)
    op.create_index(op.f('ix_workout_records_user_id'), 'workout_records', ['user_id'], unique=False)
    op.create_table('food_item_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('serving_size', sa.String(length=100), nullable=False),
    sa.Column('serving_count', sa.Float(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('quality', sa.String(length=20), nullable=False),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meal_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_item_records_meal_id'), 'food_item_records', ['meal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_item_records_meal_id'), table_name='food_item_records')
    op.drop_table('food_item_records')
    op.drop_index(op.f('ix_workout_records_user_id'), table_name='workout_records')
    op.drop_index(op.f('ix_workout_records_date'), table_name='workout_records')
    op.drop_table('workout_records')
    op.drop_index(op.f('ix_users_apple_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_correlations_user_id'), table_name='user_correlations')
    op.drop_table('user_correlations')
    op.drop_index(op.f('ix_source_priorities_user_id'), table_name='source_priorities')
    op.drop_table('source_priorities')
    op.drop_index(op.f('ix_sleep_records_user_id'), table_name='sleep_records')
    op.drop_index(op.f('ix_sleep_records_date'), table_name='sleep_records')
    op.drop_table('sleep_records')
    op.drop_index(op.f('ix_peloton_tokens_user_id'), table_name='peloton_tokens')
    op.drop_table('peloton_tokens')
    op.drop_index(op.f('ix_oura_tokens_user_id'), table_name='oura_tokens')
    op.drop_table('oura_tokens')
    op.drop_index(op.f('ix_notification_templates_context'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_category'), table_name='notification_templates')
    op.drop_table('notification_templates')
    op.drop_index(op.f('ix_notification_records_user_id'), table_name='notification_records')
    op.drop_index(op.f('ix_notification_records_category'), table_name='notification_records')
    op.drop_table('notification_records')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_meal_records_user_id'), table_name='meal_records')
    op.drop_index(op.f('ix_meal_records_date'), table_name='meal_records')
    op.drop_table('meal_records')
    op.drop_index(op.f('ix_health_metric_records_user_id'), table_name='health_metric_records')
    op.drop_index(op.f('ix_health_metric_records_source'), table_name='health_metric_records')
    op.drop_index(op.f('ix_health_metric_records_metric_type'), table_name='health_metric_records')
    op.drop_index(op.f('ix_health_metric_records_date'), table_name='health_metric_records')
    op.drop_table('health_metric_records')
    op.drop_index(op.f('ix_garmin_tokens_user_id'), table_name='garmin_tokens')
    op.drop_table('garmin_tokens')
    op.drop_index(op.f('ix_garmin_daily_records_user_id'), table_name='garmin_daily_records')
    op.drop_index(op.f('ix_garmin_daily_records_date'), table_name='garmin_daily_records')
    op.drop_table('garmin_daily_records')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_activity_records_user_id'), table_name='activity_records')
    op.drop_index(op.f('ix_activity_records_date'), table_name='activity_records')
    op.drop_table('activity_records')
    # ### end Alembic commands ###
